# Generated by Django 4.1 on 2022-09-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entrada_de_datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_contrato', models.PositiveIntegerField()),
                ('telefono', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('codigoREEUP', models.CharField(blank=True, max_length=50, null=True)),
                ('cuenta_bancaria', models.CharField(blank=True, max_length=50, null=True)),
                ('sucursal', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('municipio', models.CharField(blank=True, max_length=50, null=True)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('imagen', models.ImageField(upload_to='contratos')),
                ('created_Contrato', models.DateTimeField(auto_now_add=True)),
                ('updated_Contrato', models.DateTimeField(auto_now=True)),
                ('nombre_de_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrada_de_datos.cliente')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_etapa', models.PositiveSmallIntegerField()),
                ('cabecera', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('duracion', models.PositiveSmallIntegerField()),
                ('importe', models.PositiveBigIntegerField(blank=True, default=0.0, null=True)),
                ('numero_de_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contratacion.contrato')),
                ('participantes', models.ManyToManyField(to='Entrada_de_datos.trabajador')),
            ],
        ),
    ]
