# Generated by Django 4.1 on 2022-09-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada_de_datos', '0002_alter_categoria_docente_nombre'),
        ('Contratacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='participantes',
        ),
        migrations.AlterField(
            model_name='contrato',
            name='nombre_de_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_nombre', to='Entrada_de_datos.cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='telefono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_telefono', to='Entrada_de_datos.cliente'),
        ),
    ]
