# Generated by Django 4.1 on 2022-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratacion', '0002_remove_etapa_participantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='telefono',
            field=models.PositiveBigIntegerField(),
        ),
    ]
