# Generated by Django 4.1 on 2022-09-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratacion', '0003_alter_contrato_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero_de_contrato',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='telefono',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
