# Generated by Django 4.1 on 2022-10-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada_de_datos', '0004_alter_cliente_email'),
        ('Contratacion', '0004_alter_contrato_numero_de_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='nombre_de_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrada_de_datos.cliente'),
        ),
    ]
