# Generated by Django 4.1 on 2022-10-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contratacion', '0005_alter_contrato_nombre_de_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='codigoREEUP',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='cuenta_bancaria',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nit',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='numero_de_etapa',
        ),
        migrations.AlterField(
            model_name='etapa',
            name='cabecera',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
