# Generated by Django 4.1 on 2022-10-13 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada_de_datos', '0006_remove_trabajador_apellidos'),
        ('Contratacion', '0007_rename_nombre_de_cliente_contrato_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajadorEtapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.PositiveSmallIntegerField(default=0, verbose_name='%')),
            ],
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='imagen',
            new_name='contrato',
        ),
        migrations.RenameField(
            model_name='etapa',
            old_name='numero_de_contrato',
            new_name='contrato',
        ),
        migrations.AddField(
            model_name='contrato',
            name='resolucion',
            field=models.CharField(default='120 del 1ero de marzo de 2021', max_length=100),
        ),
        migrations.AddField(
            model_name='etapa',
            name='colaboradores',
            field=models.ManyToManyField(through='Contratacion.TrabajadorEtapa', to='Entrada_de_datos.trabajador'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero_de_contrato',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='número de contrato'),
        ),
        migrations.AlterField(
            model_name='etapa',
            name='importe',
            field=models.PositiveIntegerField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='trabajadoretapa',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contratacion.etapa'),
        ),
        migrations.AddField(
            model_name='trabajadoretapa',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrada_de_datos.trabajador'),
        ),
    ]
