# Generated by Django 4.1 on 2022-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada_de_datos', '0006_remove_trabajador_apellidos'),
        ('Contratacion', '0008_trabajadoretapa_rename_imagen_contrato_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='colaboradores',
        ),
        migrations.AddField(
            model_name='contrato',
            name='colaboradores',
            field=models.ManyToManyField(to='Entrada_de_datos.trabajador'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='contrato',
            field=models.FileField(upload_to='contratos'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='resolucion',
            field=models.CharField(default='120 del 1 de marzo de 2021', max_length=100),
        ),
        migrations.DeleteModel(
            name='TrabajadorEtapa',
        ),
    ]
