# Generated by Django 4.1 on 2022-10-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada_de_datos', '0003_remove_cliente_nombre_cliente_nombre_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
