# Generated by Django 4.1 on 2022-10-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada_de_datos', '0004_alter_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa_matriz',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='subordinada a'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigoREEUP',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=200, verbose_name='nombre de cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='titular_de_cuenta_bancaria',
            field=models.CharField(max_length=200),
        ),
    ]
