# Generated by Django 4.1 on 2022-09-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entrada_de_datos', '0001_initial'),
        ('Contratacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_factura', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=15)),
                ('codigoREEUP', models.CharField(max_length=15)),
                ('cuenta_bancaria', models.IntegerField()),
                ('sucursal', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='facturas')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('numero_de_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Entrada_de_datos.cliente')),
                ('numero_de_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contratacion.etapa')),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
            },
        ),
    ]
