# Generated by Django 4.1 on 2022-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Facturacion', '0002_rename_imagen_factura_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='codigo',
            field=models.PositiveSmallIntegerField(verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
