# Generated by Django 4.1 on 2022-09-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entrada_de_datos', '0002_alter_categoria_docente_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'lugar',
                'verbose_name_plural': 'lugares',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('propuesta', models.CharField(choices=[('1', 'Suplemento'), ('2', 'Contrato')], default='1', max_length=30)),
                ('tipo', models.CharField(choices=[('1', 'Servicio'), ('2', 'Proyecto')], default='1', max_length=30)),
                ('complejidad', models.CharField(choices=[('1', 'alta'), ('2', 'media'), ('3', 'baja')], default='1', max_length=30)),
                ('proyecto', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('tipos_de_Clientes', models.CharField(choices=[('1', 'Encargo estatal'), ('2', 'MINCIN'), ('3', 'Tercero')], default='1', max_length=30)),
                ('valor', models.PositiveIntegerField()),
                ('duracion', models.PositiveSmallIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Entrada_de_datos.cargo')),
                ('colaborador', models.ManyToManyField(to='Entrada_de_datos.trabajador')),
                ('de', models.ForeignKey(default='Departamento Filial Oriental (Santiago de Cuba)', on_delete=django.db.models.deletion.CASCADE, to='Negociacion.lugar')),
                ('ejecuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_ejecutor', to='Entrada_de_datos.trabajador')),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
            },
        ),
    ]
