# Generated by Django 4.1 on 2022-10-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Entrada_de_datos', '0004_alter_cliente_email'),
        ('Negociacion', '0002_alter_solicitud_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='cliente',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='Entrada_de_datos.cliente'),
        ),
    ]
