# Generated by Django 4.1 on 2022-11-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Negociacion', '0003_alter_solicitud_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='cargo',
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='duracion',
            field=models.PositiveSmallIntegerField(verbose_name='Duración(meses)'),
        ),
    ]
